{
 "title": "服务器PM2-List进程监控",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Stopped PM2 List",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pm2_instances{status=\"stopped\"}"
    }
   ]
  },
  {
   "title": "终止的进程数量 ",
   "type": "gauge",
   "description": "SUM(pm2_instances{status=\"stopped\"})",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "SUM(pm2_instances{status=\"stopped\"})"
    }
   ]
  },
  {
   "title": "PM2进程状态",
   "type": "table",
   "description": "PM2进程是否运行中\nisUp: 1 运行中\nisUp: 0 停止",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "pm2_instances" }
   ]
  }
 ]
}